DROP SCHEMA IF EXISTS nontoncom120510210038;
CREATE SCHEMA nontoncom120510210038;

CREATE USER 'nontoncom111'@'localhost' IDENTIFIED BY 'nontoncom';
GRANT ALL ON nontoncom120510210038.* TO 'nontoncom111'@'localhost';
CREATE USER 'nontoncom111'@'127.0.0.1' IDENTIFIED BY 'nontoncom';
GRANT ALL ON nontoncom120510210038.* TO 'nontoncom111'@'127.0.0.1';

USE nontoncom120510210038;

create table videos
(
    id       int auto_increment
        primary key,
    title    varchar(100)  not null,
    poster   varchar(200)  not null,
    teaser   varchar(1000) not null,
    type     varchar(10)   not null,
    genre    varchar(100)  not null,
    rating   varchar(10)   not null,
    director varchar(100)  not null,
    actor    varchar(200)  not null,
    video    varchar(1000) not null
);

INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (1, 'His People''s Terraforming Bomb', 'valdas-jokubaitis-soldier.jpg', 'In a distant planet, a native must warn Earth of an impending hostile terraforming campaign launched by his own kind.', 'film', 'Sci-fi', 'LSF 13+', 'Sigimund Tlaghish', 'Mogg Herna', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (2, 'Elec', 'elec-1.jpg', 'The adventures of a technomage across the ruins of the Ecosystem.', 'film', 'Sci-fi', 'LSF 13+', 'Eoin Stellrecht', 'Grasp Ma', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (3, 'Elec: Inheritor', 'elec-2.jpg', 'Elec meets new friends as they begin to revive the Ecosystem.', 'film', 'Sci-fi', 'LSF 13+', 'Eoin Stellrecht', 'Grasp Ma', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (4, 'Elec: Final Wars', 'placeholder.jpg', 'A cosmic horror comes to the Ecosystem, and it''s up to Elec and his gang to stop it.', 'film', 'Sci-fi', 'LSF 13+', 'Eoin Stellrecht', 'Grasp Ma', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (5, 'Elec: Coda', 'placeholder.jpg', 'The final chapter of the Elec saga.', 'film', 'Sci-fi', 'LSF 13+', 'Eoin Stellrecht', 'Grasp Ma', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (6, 'Nik and the Artificially-Intelligent Assistant', 'arnaud-caubel-cypressisle.jpg', 'In the middle of a Luddite revolution against computers in general, Nik escapes to another planet, a mythical planet where computers are still in use.', 'film', 'Sci-fi', 'LSF 13+', 'Ealdraed Evoo', 'Dan Redev', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (7, 'Clones', 'placeholder.jpg', 'A clone rebels against his creator, and he has ally rebels...', 'film', 'Sci-fi', 'LSF 17+', 'Ealdraed Evoo', 'Chorhert Nunah', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (8, 'Meet Me at the Mall', 'placeholder.jpg', 'A nostalgia ride through the nineties.', 'film', 'Documentary', 'LSF SU', 'Aethelbehrt All', 'Dan Marugawa', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (9, 'Never Gonna Give You Up', 'placeholder.jpg', 'A teenage love story', 'film', 'Romance', 'LSF 13+', 'Egilhard Chaibun', 'Udhuq Strost', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (10, 'My Way, Promises! Or: The Fall of the Galactic Empire', 'placeholder.jpg', 'The adoption of a universal religion and the gradual decommissioning of computers become the catalysts of the fall of the Galactic Empire.', 'film', 'Sci-fi', 'LSF 13+', 'Eoin Stellrecht', 'Har Wakhiaq', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (11, 'Hotel Viewplace', 'placeholder.jpg', 'A hotel guest becomes the centerpiece of a murder he didn''t do.', 'film', 'Thriller', 'LSF 17+', 'Trym Qyroo', 'Reinhard Zoothu', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (12, 'Expressway T1', 'reuben-lane-crane-1-copy-save-as.jpg', 'The Trunk Line Through Expressway.', 'film', 'Documentary', 'LSF SU', 'Trym Qyroo', 'N/A', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (13, 'Nature and Empire...', 'terraform-studios-030822-xaya-floating-islands-alt-2-qm.jpg', 'A Terran must choose between saving his dystopian homeworld or the planet he''s stationed in. Most grossing film in the Terran Combine since its release.', 'film', 'Sci-fi', 'LSF 13+', 'Eoin Stellrecht', 'Vanshatu Kyderson', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (14, 'Warriors Beyond', 'min-seub-jung-hemi-house-151.jpg', 'A Whirosian Central Empire elite force must attempt to secure the colonization of a planet inhabited by large nonsentient insects.', 'film', 'Sci-fi', 'LSF 13+', 'Trym Qyroo', 'Lounda Thugos', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (15, 'Stand By for Mars!', 'placeholder.jpg', 'The bootcamp of new cadets of the Solar Guard.', 'film', 'Sci-fi', 'LSF 13+', 'Vark Razed', 'Vanshatu Kyderson', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (16, 'This Island Terra', 'placeholder.jpg', 'An engineer builds a strange machine that will take him to other worlds.', 'film', 'Sci-fi', 'LSF 13+', 'Odilo Ksuchkad', 'Vanshatu Kyderson', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (17, 'Only Solutions', 'placeholder.jpg', 'A gas attack in the Muni Subway and its afternath.', 'film', 'Thriller', 'LSF 17+', 'Aethelweald Shija', 'Wynnstan Eqnais', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (18, 'Cyber Riot Force', 'michal-kvac-huge-city-buildings-small.jpg', 'A policeman gets tasked to investigate a mass shooting that is apparently motivated by science fiction.', 'film', 'Sci-fi', 'LSF 17+', 'Eoin Stellrecht', 'Had''is Da', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (19, 'They Chose Ours', 'placeholder.jpg', 'The secrets of the Ryokutsu zaibatsu.', 'film', 'Documentary', 'LSF SU', 'Meginhard Deonfe', 'N/A', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (20, 'The Dash Way', 'shubham-parte-viking-village-entrance1.jpg', 'An alien landed in Viking era Terra.', 'film', 'Sci-fi', 'LSF 13+', 'Albert Saegnex', 'Chorhert Nunah', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (21, 'Retvrn', 'placeholder.jpg', 'A revolution.', 'film', 'Sci-fi', 'LSF 17+', 'Aethelweald Shija', 'Jim Griffin', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (22, 'Escape Across the Cosmos', 'shahab-alizadeh-fridaysketch.jpg', 'A single silicon superman against the advancing terror of the Slarrn World.', 'film', 'Sci-fi', 'LSF 13+', 'Fulbert Getho', 'Jim Griffin', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (23, 'Wanderer', 'shahab-alizadeh-sketch-sd.jpg', 'The life of a warrior without command, as the Coalition falls down.', 'film', 'Sci-fi, Military', 'LSF 13+', 'Aethelweald Shija', 'Loo Kayne', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (24, 'Make Me Love You', 'placeholder.jpg', 'Distances doesn''t matter when you''re dealing with love. A cyberpunk romance film.', 'film', 'Sci-fi, Romance', 'LSF 13+', 'Eoin Stellrecht', 'Dan Redev', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (25, 'Wanderer 2', 'shahab-alizadeh-qwdaqsdqwdaqsd.jpg', 'As the old Coalition worlds begin to be reconnected, the Wanderer settles in an once-important outpost.', 'film', 'Sci-fi, Military', 'LSF 13+', 'Aethelweald Shija', 'Loo Kayne', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (26, 'For the Greater Good?', 'william-kalkanis-ellis-paintover-008-window.jpg', 'Necromancers attack a village claiming "for the greater good."', 'film', 'Fantasy', 'LSF 13+', 'Ansehelm Eadwo', 'Adalbehrt Sechu', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (27, 'Theft Revolutionized', 'placeholder.jpg', 'The evolution of computer-based theft.', 'film', 'Documentary', 'LSF SU', 'Wendelin Uzothaadh', 'N/A', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (28, 'Exposure', 'vadim-sadovski-alien-exposure-exposure.jpg', 'Depressed spirits and astronauts...', 'film', 'Sci-fi, Fantasy, Horror', 'LSF 17+', 'Eoin Stellrecht', 'Udhuq Strost', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (29, 'The Conspired', 'placeholder.jpg', 'A prequel to Escape Across the Cosmos.', 'film', 'Sci-fi, Military', 'LSF 13+', 'Fulbert Getho', 'Jim Griffin', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (30, 'Mooncrash', 'munpol.jpg', 'Spin-off of This Island Terra focusing on the Systems Combine crew on the Moon.', 'film', 'Sci-fi', 'LSF 13+', 'Ealdraed Evoo', 'Vanshatu Kyderson', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (31, 'Warrior of Llarn', 'placeholder.jpg', 'A mission to a planet gone wrong', 'film', 'Sci-fi', 'LSF 17+', 'Ealdraed Evoo', 'Jim Griffin', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (32, 'Mana Harnessed ', 'wadim-kashin-manafin.jpg', 'An attempt to harness the power of the ether by medieval people... with a little help by extraterrestrials.', 'film', 'Sci-fi', 'LSF 13+', 'Vulfgang Budoein', 'Winfrith Edip', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (33, 'Thief of Llarn', 'placeholder.jpg', 'Sequel to Warrior of Llarn', 'film', 'Sci-fi', 'LSF 17+', 'Ealdraed Evoo', 'Jim Griffin', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (34, 'Run Among the Ruins', 'sathish-kumar-4.jpg', 'The ruins of an alien attack is really a thrilling place to explore!', 'film', 'Sci-fi', 'LSF 13+', 'Meginhard Deonfe', 'Jim Griffin', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (35, 'Dash Blaster', 'placeholder.jpg', 'Training in the DASHBLASTER School', 'film', 'Military', 'LSF 13+', 'Thrymr Yugiah', 'Vanshatu Kyderson', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (36, 'Integrate', 'a_ghost_by_darkgeometryart_d6v2tno.jpg', 'Integration of Earth into the Whirosian Central Empire', 'film', 'Sci-fi', 'LSF 13+', 'Vulfgang Budoein', 'Jim Griffin', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (37, 'Elsewhere', 'sathish-kumar-5.jpg', 'A journey into the Lands of the Damned', 'film', 'Fantasy', 'LSF 13+', 'Wendelin Uzothaadh', 'Dan Marugawa', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (38, 'White Shadow', 'placeholder.jpg', 'The death of Rick''s father motivates him into fighting for good.', 'film', 'Action', 'LSF 13+', 'Ealdraed Evoo', 'Reinhard Zoothu', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (39, 'Transport Zero', 'valdas-jokubaitis-warp-linker-08-tilt-shift.jpg', 'A rogue transport ship chase', 'film', 'Sci-fi, Thriller', 'LSF 13+', 'Sigimund Tlaghish', 'Lounda Thugos', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (40, 'Voltage', 'placeholder.jpg', 'A new superhero is born.', 'film', 'Superhero', 'LSF 13+', 'Odo Gzaghbog', 'Ken Razed', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (41, 'Otherworlds', 'placeholder.jpg', 'Escape from the tyrannical government of a distant planet.', 'film', 'Sci-fi', 'LSF 13+', 'Fulbert Getho', 'Reinhard Zoothu', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (42, 'Soldier from Tomorrow', 'placeholder.jpg', 'A war-hating soldier from the far future, conditioned from birth to wage war, accidentally gets time-warped into the present.', 'film', 'Sci-fi', 'LSF 17+', 'Eoin Stellrecht', 'Idalia Azad', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (43, 'We''re Going To...', 'daniele-gay-onthehillvert2.jpg', 'A UFO abduction turns into an interstellar adventure for a farmer.', 'film', 'Sci-fi', 'LSF 13+', 'Eoin Stellrecht', 'Had''is Da', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (44, 'Voltage and the Hyperians', 'placeholder.jpg', 'Sequel to Voltage', 'film', 'Superhero', 'LSF 13+', 'Witold Chaipum', 'Ken Razed', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (45, 'Moment', 'daniele-gay-need-a-recharge.jpg', 'A day in the life of a warrior of the Empire', 'film', 'Sci-fi', 'LSF 13+', 'Ansehelm Eadwo', 'Helgi Bouqi', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (46, 'You''re Late', 'no-one-stays-clean.jpg', 'A policeman''s life gets slightly ruined when he is late for attendance.', 'film', 'Sci-fi, Cyberpunk', 'LSF 13+', 'Odilo Ksuchkad', 'Grasp Ma', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (47, 'The Thirteenth Planet', 'placeholder.jpg', 'The tale of the colonization of Terra by human-looking aliens.', 'film', 'Sci-fi', 'LSF 13+', 'Eoin Stellrecht', 'Crim Anderson', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (48, 'Martian Defense Force', 'daniele-gay-boh.jpg', 'An inhabitant of a secret German Mars colony enlists in the Martian defense force.', 'film', 'Sci-fi', 'LSF 13+', 'Trym Qyroo', 'Vark Razed', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (49, 'The City and the Stars', 'placeholder.jpg', 'An inhabitant of a utopian city travels off-limits.', 'film', 'Sci-fi', 'LSF 13+', 'Egilhard Chaibun', 'Dan Marugawa', 'rick.mp4');
INSERT INTO nontoncom120510210038.videos (id, title, poster, teaser, type, genre, rating, director, actor, video) VALUES (50, 'Strangers from the Skies', 'placeholder.jpg', 'Are UFOs watching our civilization?', 'film', 'Documentary', 'LSF 13+', 'Albert Saegnex', 'N/A', 'rick.mp4');
